export const USERINFO_LOGIN = 'USERINFO_LOGIN';
export const UPDATE_CITYNAME = 'UPDATE_CITYNAME';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const USER = 'USER';
export const FETCHLOADING = 'FETCHLOADING';
export const FETCHUSERFAILURE = 'FETCHUSERFAILURE';
export const TOKEN = 'TOKEN'; // 设置用户token
export const SETEDITORSTATE = 'SETEDITORSTATE';